# Generated by Django 5.0.7 on 2026-06-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='artifacts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
