# Generated by Django 5.0.7 on 2026-06-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='developer_key',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='developer_level',
            field=models.CharField(blank=True, choices=[('junior', 'Джуниор'), ('middle', 'Мидл'), ('senior', 'Сеньор')], max_length=16, null=True),
        ),
    ]
