# Generated by Django 5.0.7 on 2026-06-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_developer_key_user_developer_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='developer_level',
            field=models.CharField(blank=True, choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], max_length=16, null=True),
        ),
    ]
