events {}

http {
    client_max_body_size 20m;

    upstream backend_upstream {
        server backend:8000;
    }

    upstream frontend_upstream {
        server frontend:5173;
    }

    server {
        listen 80;

        location /api/ {
            proxy_pass http://backend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /ws/ {
            proxy_pass http://backend_upstream;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_read_timeout 3600s;
        }

        location /admin/ {
            proxy_pass http://backend_upstream;
            proxy_set_header Host $host;
        }

        location /static/ {
            proxy_pass http://backend_upstream;
        }

        location / {
            proxy_pass http://frontend_upstream;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
