# Generated by Django 5.0.7 on 2026-06-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(choices=[('user', 'Пользователь'), ('ai', 'ИИ-помощник'), ('developer', 'Разработчик'), ('system', 'Системное сообщение')], max_length=16),
        ),
    ]
