# Generated by Django 5.0.7 on 2026-06-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0002_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
