# Generated by Django 5.0.7 on 2026-06-22 02:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_chat', '0003_chatsession_closed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='category',
            field=models.CharField(choices=[('question', 'Вопрос по языку или документации'), ('site_broken', 'Не работает сайт или личный кабинет'), ('language_bug', 'Баг в языке или компиляторе'), ('critical', 'Критично: потерян доступ или данные')], default='question', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='waiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
