# Generated by Django 5.0.7 on 2026-06-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspost',
            options={'ordering': ('-published_at', '-created_at')},
        ),
        migrations.AddField(
            model_name='newspost',
            name='cover_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='newspost',
            name='summary',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='newspost',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
