# Generated by Django 5.0.7 on 2026-06-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_newspost_options_newspost_cover_image_and_more"),
    ]

    operations = [
        # без unique=True пока — на существующих строках слаг ещё пустой,
        # уникальность включаем отдельной миграцией 0005 после бэкафилла
        # в 0004 (иначе ALTER TABLE упадёт на дублирующихся пустых строках)
        migrations.AddField(
            model_name="newspost",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, default=""),
        ),
    ]
