# Generated by Django 5.0.7 on 2026-06-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_backfill_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
