# Generated by Django 5.0.7 on 2026-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newspost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='blocks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
