# Generated by Django 5.0.7 on 2026-06-22 14:27

import apps.forum.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_topic_slugs(apps, schema_editor):
    # на момент написания миграции slug ещё не unique — заполняем его для
    # уже существующих записей (demo-данные), прежде чем следующая операция
    # наложит unique-ограничение, иначе несколько пустых строк его нарушат
    from apps.news.models import transliterate

    Topic = apps.get_model('forum', 'Topic')
    for topic in Topic.objects.all():
        base = slugify(transliterate(topic.title)) or 'topic'
        slug = base
        counter = 1
        while Topic.objects.filter(slug=slug).exclude(pk=topic.pk).exists():
            counter += 1
            slug = f'{base}-{counter}'
        topic.slug = slug
        topic.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reference_line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='blocks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, default='', db_index=False),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_topic_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='summary',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='topic',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ForumAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.forum.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.topic')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='reference_attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_references', to='forum.forumattachment'),
        ),
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_categories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'forum categories',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='forum.forumcategory'),
        ),
        migrations.CreateModel(
            name='ForumRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='forum.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('topic', 'user')},
            },
        ),
    ]
