# Generated by Django 5.0.7 on 2026-06-24 08:14

import django.db.models.deletion
from django.db import migrations, models


def migrate_single_reference_to_comment_reference(apps, schema_editor):
    """Переносим старое одно reference_attachment/reference_line на комментарий
    в новую модель CommentReference (start_line=end_line=reference_line) —
    до того, как старые поля будут удалены ниже."""
    Comment = apps.get_model('forum', 'Comment')
    CommentReference = apps.get_model('forum', 'CommentReference')
    for c in Comment.objects.exclude(reference_attachment__isnull=True):
        line = c.reference_line or 1
        CommentReference.objects.create(
            comment=c, attachment_id=c.reference_attachment_id, start_line=line, end_line=line,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_comment_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_line', models.PositiveIntegerField()),
                ('end_line', models.PositiveIntegerField()),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_references', to='forum.forumattachment')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='forum.comment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RunPython(migrate_single_reference_to_comment_reference, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='comment',
            name='reference_attachment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reference_line',
        ),
    ]
