# Generated by Django 5.0.7 on 2026-06-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_comment_reference_attachment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReference',
        ),
    ]
